git:
  push: true
  requireBranch: main
  commit: true
  commitMessage: release ${version}
  commitArgs: ["--no-verify"]

github:
  release: true

npm:
  publish: true

before:init:
  - yarn lint
  - yarn format
  - yarn typecheck
  - yarn clean
  - yarn build
